#!/bin/bash
# Zeus Decision Graph Daily Regeneration
# Runs daily to update zeus_decision_graph.json from embedded Zeus memories
#
# This script:
# 1. Extracts latest decisions and CCE memories from Zeus Memory
# 2. Generates similarity edges using pgvector embeddings
# 3. Creates 3D visualization HTML
# 4. Commits and pushes to trigger GitHub Actions deployment
#
# Schedule: Daily at 4 AM (after batch embedder completes)
# Crontab: 0 4 * * * /home/aldc/repos/athena/regen_zeus_graph.sh >> /var/log/athena-regen.log 2>&1

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_PREFIX="[$(date '+%Y-%m-%d %H:%M:%S')] Athena Regen:"
cd "$SCRIPT_DIR"

echo "$LOG_PREFIX Starting Zeus decision graph regeneration"

# Activate venv if exists
if [ -f "$SCRIPT_DIR/venv/bin/activate" ]; then
    source "$SCRIPT_DIR/venv/bin/activate"
fi

# Step 1: Extract Zeus data (queries embedded memories for similarity edges)
echo "$LOG_PREFIX Step 1: Extracting Zeus data..."
python3 src/extract_zeus_data.py \
    --output data/examples/zeus_decision_graph.json

# Check if extraction produced output
if [ ! -f "data/examples/zeus_decision_graph.json" ]; then
    echo "$LOG_PREFIX ERROR: Failed to generate zeus_decision_graph.json"
    exit 1
fi

NODE_COUNT=$(python3 -c "import json; print(len(json.load(open('data/examples/zeus_decision_graph.json'))['nodes']))")
EDGE_COUNT=$(python3 -c "import json; print(len(json.load(open('data/examples/zeus_decision_graph.json'))['edges']))")
echo "$LOG_PREFIX Extracted $NODE_COUNT nodes and $EDGE_COUNT edges"

# Step 2: Generate 3D visualization HTML
echo "$LOG_PREFIX Step 2: Generating 3D visualization..."
python3 src/generate_3d.py \
    --input data/examples/zeus_decision_graph.json \
    --output output/html/zeus_decision_graph.html

if [ ! -f "output/html/zeus_decision_graph.html" ]; then
    echo "$LOG_PREFIX ERROR: Failed to generate zeus_decision_graph.html"
    exit 1
fi

echo "$LOG_PREFIX Generated HTML: $(wc -c < output/html/zeus_decision_graph.html) bytes"

# Step 3: Check for changes
if git diff --quiet data/examples/zeus_decision_graph.json output/html/zeus_decision_graph.html 2>/dev/null; then
    echo "$LOG_PREFIX No changes detected, skipping commit"
    exit 0
fi

# Step 4: Commit and push
echo "$LOG_PREFIX Step 4: Committing changes..."
git add data/examples/zeus_decision_graph.json output/html/zeus_decision_graph.html
git commit -m "Auto-regenerate Zeus decision graph - $(date '+%Y-%m-%d %H:%M')

Nodes: $NODE_COUNT
Edges: $EDGE_COUNT

Generated by daily cron job.
Co-Authored-By: CCE <noreply@aldc.io>"

echo "$LOG_PREFIX Pushing to trigger deployment..."
git push origin main

echo "$LOG_PREFIX Complete! Graph will be available at https://athena.aldc.io/viz/zeus after deployment"
